import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "@/globals.css";
import styles from "./layout.module.css";
import Navbar from "@/components/navbar/navbar";
import AuthProvider from "@/providers/AuthProvider";
import { NextIntlClientProvider } from "next-intl";
import { cookies } from "next/headers";
import LanguageSelect from "@/components/langSwitch/langSwitch";

const sourceSans3 = Source_Sans_3({
	subsets: ["latin"],
	display: "swap", // or 'fallback', 'optional', 'block'
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const locale = (await cookies()).get("locale")?.value ?? "en";

	return (
		<html lang="en" suppressHydrationWarning>
			<body className={sourceSans3.className}>
				<AuthProvider>
					<NextIntlClientProvider>
						<Navbar />
						<div className={styles.container}>
							<LanguageSelect value={locale} />
							{children}
						</div>
					</NextIntlClientProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
