import type { Metadata } from "next";
import { Source_Sans_3 } from "next/font/google";
import "../globals.css";
import styles from "./home.module.css";
import Navbar from "@/components/navbar/navbar";
import AuthProvider from "@/providers/AuthProvider";
const sourceSans3 = Source_Sans_3({
  subsets: ["latin"],
  display: "swap", // or 'fallback', 'optional', 'block'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={sourceSans3.className}>
        <AuthProvider>
          <Navbar />
          <div className={styles.container}>
            <div className={styles.main}>{children}</div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
